---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-tr
spec:
  replicas: 1
  selector:
    matchLabels:
      app:
        hello-tr
  template:
    metadata:
      labels:
        app: hello-tr
    spec:
      containers:
        - name: greg-tr
          image: 898846401548.dkr.ecr.eu-central-1.amazonaws.com/simple-tr:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hello-tr

---
kind: Service
apiVersion: v1
metadata:
  name: hello-tr
spec:
  type: NodePort
  selector:
    app: hello-tr
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-tr
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: hello-tr
spec:
  rules:
    - host: "hello.guang.tr-talent.de"
      http:
        paths:
          - path:
            backend:
              serviceName: hello-tr
              servicePort: 8080